### ISSUE TITLE
Permission to Deploy and Monetize

### ISSUE THREAD

**Issue by Zain-ul-din** [imputnet/cobalt#582]
This project is fantastic, and I appreciate all the hard work that has gone into it. I want to deploy my own version of this project and run ads on it to cover the server costs associated with deployment.

Could you please let me know if the current license permits this, or not?

**Comment by wukko** [comment]
absolutely not

**Comment by Zain-ul-din** [comment]
Sorry for sending message one more time, As mention in readme if you want to run ads deploy your own version what does that means?

![image](https://github.com/imputnet/cobalt/assets/78583049/40438c47-d946-4d37-a2d5-ff2bc71c03c7)

**Comment by ihatespawn** [comment]
based on the content of that message, you can do that but **you need to host your own instance** (that means you can't use api.cobalt.tools and probably other instances too because no one likes when you use something that they pay for for profit and they will probably block it).

how to run your own instance: https://github.com/imputnet/cobalt/blob/current/docs/run-an-instance.md

also,
> cobalt branding, mascots, and other related assets included in the repo are copyrighted and not covered by the AGPL-3.0 license. you cannot use them under same terms.

> when making an alternative version of the project, please replace or remove all branding (including the name).

> if you make a modified version of cobalt, the codebase must be published under the same license (according to AGPL-3.0).

**Comment by Zain-ul-din** [comment]
@ihatespawn Thank you for your reply. Sure I'll manage to deploy my own instance.
