### ISSUE TITLE
Help How to generate cookie.json file for youtube?

### ISSUE THREAD

**Issue by nikunjgupta586** [imputnet/cobalt#687]
### problem description
Can someone tell me the steps to create cookie.json file for youtube? I mean How can I generate token from youtube and in which format should I store it into cookie.json file?

**Comment by KwiatekMiki** [comment]
`npm run token:youtube`

You will get a token looking like this:
> access_token=somestuff; refresh_token=morestuff; scope=https://www.googleapis.com/auth/youtube <https://www.googleapis.com/auth/youtube-paid-content>; token_type=Bearer; expiry_date=randomdateyoudontneedtocareabout

and put it in cookies.json like this:
```json
{
    "youtube_oauth": [
        "access_token=somestuff; refresh_token=morestuff; ..."
    ]
}
```

**Comment by wukko** [comment]
do NOT use personal google account btw

**Comment by MHemelHasan** [comment]
Hey @KwiatekMiki , If I didn't use docker an instance of clone the git repo and run from there then where should I create the cookies.json file,
in my repo, I found "cobalt\api\src\processing\cookie" and that cookie folder has a cookie.js and manager.js

I follow this instruction
Run npm run token:youtube in the same terminal as before
(do cd cobalt/api if you already closed it or if you skipped the above)
Log in with the account just for cobalt

generate the "youtube_oauth" but I couldn't put it in cookies.json because in my repo it doesn't have, And I didn't find any instruction where should I create or how to generate.

One more thing when I generate the youtube_oauth by running that commends "npm run token:youtube", and following the step it successfully generates it. It also has a cookie expiration time in my case that was 1 day meaning 24 hours. If so then it's really a problem if need to update the cookies every 24 hours. 
Am I missing something or are there options that automatically update the cookie.json file

**Comment by Haoran1272** [comment]
@MHemelHasan You need to configure the path to the cookies.json in .env file, like "COOKIE_PATH = /www/cobalt/api/cookies.json".
