### ISSUE TITLE
Module not found, Path issue

### ISSUE THREAD

**Issue by nikunjmishra1998** [imputnet/cobalt#751]
### bug description

when we run 'npm run setup' command then below error throws
error : Cannot find module 'D:\NewCobalt\cobalt\api\src\util\misc\console-text.js' imported from D:\NewCobalt\cobalt\api\src\util\setup.js

given Include path is wrong in 'D:\NewCobalt\cobalt\api\src\util\setup.js' of 'D:\NewCobalt\cobalt\api\src\util\misc\console-text.js'
where 'console-text.js' is located in 'D:\NewCobalt\cobalt\api\src\misc\console-text.js'. 
'\util\' is coming extra in path

### reproduction steps

1) clone code in local.
2) install node modules using 'pnpm install'
3) run 'npm run setup' command and issue throws 

### screenshots

![image](https://github.com/user-attachments/assets/a48d453e-9f18-448f-86af-0fa81ee884a7)

### platform information

Any operating system

**Comment by wukko** [comment]
the setup script is (currently) outdated, not recommended to use with v10 cobalt, and is also not mentioned in the docs anymore. we recommend manually creating the .env file, as mentioned in the [local hosting tutorial](https://github.com/imputnet/cobalt/blob/main/docs/run-an-instance.md#run-cobalt-api-outside-of-docker-useful-for-local-development).

the bug with an invalid module path was fixed by #748.

**Comment by wukko** [comment]
> NewCobalt

![image](https://github.com/user-attachments/assets/562214c7-90fa-4056-87f6-cfa183325a95)
