### ISSUE TITLE
Unable to download long vedio in youtube

### ISSUE THREAD

**Issue by Deepalwije123** [imputnet/cobalt#960]
### bug description

Unable to download following vedio even in 480p in h264

link:  https://youtu.be/CWyjJR6VEpM

### reproduction steps

1. Open https://cobalt.tools/
2. Change vedio settings to 480p and h264
3. Put following url , https://youtu.be/CWyjJR6VEpM
4. It only download partial vedio , not the full lenghth vedio ( arround 4 hours) 

### platform information

Ios 18.1.1 safari

**Comment by raymukh** [comment]
+1

**Comment by Vladutzu27** [comment]
I am making a presentation and i need clips from various 40-50 minutes long clips, and the length of the resulting video the site downloads is variable, as well as its file size.

![downloads with variable sizes](https://github.com/user-attachments/assets/3833d34b-a2ac-4b46-abf6-82b88029767a)

**Comment by YggdrasilsHeart** [comment]
Can concur with this error, so just gonna add some more data:

Reproduction steps are same as before but using Audio instead of Video
Files come out the same length (26:21) and same file size (24,709 kb)

Specific Video: [](https://youtu.be/36oEl09BcrA?si=wBk1V7tRVZ5WiBYq)
![image](https://github.com/user-attachments/assets/3f2eae13-4b1b-4ef9-8af8-277d5ec0dcc2)

**Comment by wukko** [comment]
using the hls option helps fix randomly cutting off videos: https://cobalt.tools/settings/video#youtube-hls

will probably have to enable it by default soon
